% Script for printing on terminal key data

if isnan(mean0)
    mean0ToDisp = -1;
else
    mean0ToDisp = mean1;
end

if isnan(mean1)
    mean1ToDisp = -1;
else
    mean1ToDisp = mean1;
end

disp( "Max ET [s]       : " + max_time_exe + newline + ...
      "Min ET [s]       : " + min_time_exe + newline + ...
      "Mean ET [s]      : " + mean_tot_time + newline + ...           
      "Mean ET N_l [s]  : " + mean0ToDisp + newline + ...
      "Min ET N_s [s]   : " + mean1ToDisp + newline + ...
      "Total ET [s]     : " + tot_ex_time + newline + ...
      "Max f_e [s]      : " + max_form_err*10^3 + newline + ...
      "Mean f_e [s]     : " + mean_form_err*10^3 + newline ...
    )