% Script for printing on terminal key data

mean0ToDisp = -1;
mean1ToDisp = -1;

disp( "Max ET [s]       : " + max_time_exe + newline + ...
      "Min ET [s]       : " + min_time_exe + newline + ...
      "Mean ET [s]      : " + mean_tot_time + newline + ...           
      "Mean ET N_l [s]  : " + mean0ToDisp + newline + ...
      "Mean ET N_s [s]  : " + mean1ToDisp + newline + ...
      "Total ET [s]     : " + tot_ex_time + newline + ...
      "Max FE [mm]      : " + max_form_err*10^3 + newline + ...
      "Mean FE [mm]     : " + mean_form_err*10^3 + newline + ...
      "Min dist [mm]    : " + my_min_obs_dist*10^3 + newline ...     
    )